# Start with a rustup image providing the stable release.
image: ${CI_REGISTRY}/kaios/sidl:1.66.1_9_0 

# Environment variables
variables:
  GIT_SUBMODULE_STRATEGY: normal
  CARGO_HOME: $CI_PROJECT_DIR/cargo

# Setup SSH key to access git
before_script:
  - echo -e "machine ${CI_SERVER_HOST}\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc

stages:
  - build_and_test

# Use cargo to test the project
test:cargo:
  stage: build_and_test
  script:
  - export PATH=$CARGO_HOME/bin:$PATH
  - rustc --version && cargo --version
  - cargo build --release
  - RUST_BACKTRACE=1 cargo test --release -- --nocapture

