[package]
name = "zip_utils"
version = "0.1.0"
authors = ["Fabrice Desré <fabrice@desre.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
base64 = "0.12"
zip = { git = "ssh://git@git.kaiostech.com/rust-forks/zip-rs.git", branch="omni-ja", default-features = false, features = ["deflate", "omnija"]}
ring = "0.16"
untrusted = "0.7"
simple_asn1 = "0.4.0"
chrono = "0.4"
x509-signature = "0.5"
hex-slice = "0.1.4"


[patch.crates-io]
# Unbreak build on Gonk.
ring = { git = "https://github.com/kaiostech/ring.git", branch = "gonk-0.16.15" }